### ISSUE TITLE
Document Zone skybox texture layout(s)

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/vircadia-docs-sphinx#14]

**Comment by ctrlaltdavid** [comment]
Is it per the following?

![image](https://user-images.githubusercontent.com/7455448/73637211-a1cc1280-46cc-11ea-84bf-f13a4cb800db.png)

**Comment by odysseus654** [comment]
I've used the vertical format described here with it appearing to work https://docs.unity3d.com/Manual/class-Cubemap.html

**Comment by HifiExperiments** [comment]
I think equirectangular also works?  if the width = 2 * the height, I believe
