### ISSUE TITLE
"Add a Skybox to a Zone" is incomplete and/or wrong

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/vircadia-docs-sphinx#46]
Following the "Add a Skybox to a Zone" documentation, allows setting a color as skybox, but trying to add an image does not work.
All domains I have gone to have either set an image directly, or used a completely different json.
There seem to be restrictions on what images are loaded as a skybox as well.
[pont+d'lena.jpg](https://photosphere-cubemap.s3-us-west-1.amazonaws.com/pont+d'lena.jpg) as seen in the Trivia Pub can be loaded, but [purple_nebula_skybox_front.png](http://motofckr9k.ddns.net/m/vircadia/purple_nebula_skybox_front.png) and [purple_nebula_skybox_front.jpg](http://motofckr9k.ddns.net/m/vircadia/purple_nebula_skybox_front.jpg) cannot be loaded.

https://docs.vircadia.dev/create/entities/zone-tutorial.html?highlight=skybox#add-a-skybox-to-a-zone

I will try to get some info on this in the maker meeting.

EDIT: Seems like it need an image in 2:1 aspect ratio as [purple_nebula_skybox_front_WIDE.png](http://motofckr9k.ddns.net/m/vircadia/purple_nebula_skybox_front_WIDE.png) works.

**Comment by AleziaKurdis** [comment]
For skyboxes, two formats are supported: 
- "**Cubemap**" (Ratio 4:3) 
![CubeLayout6Faces](https://user-images.githubusercontent.com/60075796/81018418-78896280-8e32-11ea-80d8-114cc2aa400d.png)

- "**Equirectanglar**" (Ratio 2:1)
![message-1607747-16122375658974776106](https://user-images.githubusercontent.com/60075796/81018523-aff80f00-8e32-11ea-8087-d4feca869cef.jpg)

The system detect which method to apply based on the **ratio** of the image.
If the ratio of the image file is not matching exactly one of these 2 ratios (2:1 or 4:3), then it will be ignored and won't be displayed.
