### ISSUE TITLE
docs.vircadia.dev does not redirect to secure page

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/vircadia-docs-sphinx#80]
http://docs.vircadia.dev does not redirect to https://docs.vircadia.dev

**Comment by kasenvr** [comment]
It did for me, how do you replicate that behavior?

**Comment by JulianGro** [comment]
It does now. It also loads a LOT faster now.

**Comment by kasenvr** [comment]
I didn't do anything, but for speed I wiped about 20GB of junk when I finally found out where it was so there's that.

**Comment by JulianGro** [comment]
It was apparently the Firefox on my other system, but this doesn't happen since updating it.
